### ISSUE TITLE
Not accessing translation

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#1]
Copying this over (from idp.data issues, where it was submitted by Rodney) to the sosol issues, because I am pretty sure it is an editor thing.

I cannot access translations on my dashboard, http://www.papyri.info/editor/user/board_dashboard?board_id=3

I just get this error message

"We're sorry, but something went wrong.

We've been notified about this issue and we'll take a look at it shortly.

You should be redirected momentarily."

**Comment by jcowey** [comment]
It should be noted that the XML of the translation can be accessed, voted upon and finalized. Preview button works as well.

**Comment by ryanfb** [comment]
Fix should now be live.
