### ISSUE TITLE
Files not properly processed

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#109]
The following files in the HGV board do not allow me to make myself finalizer. They are in the Approved section but do not budge from there:

 - [x] http://papyri.info/editor/publications/65519/hgv_meta_identifiers/148289/edit
 - [x] http://papyri.info/editor/publications/64463/hgv_meta_identifiers/145937/edit
 - [x] http://papyri.info/editor/publications/65891/hgv_meta_identifiers/149223/edit

And this one got caught in waiting, although I gave it the HGVaccept vote (i.e. straight to finalization)

 - [x] http://papyri.info/editor/publications/65190/hgv_meta_identifiers/147587/edit

Would you please free them up and assign them all to me 
http://papyri.info/editor/users/james.cowey

This is all on the HGV board (not that I suppose that makes much difference to what you do).

Thanks

**Comment by ryanfb** [comment]
Should all be fixed now!
