### ISSUE TITLE
Unusual error

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#122]
time stamp of 15.22 or maybe 15.21 or 15.23 

I assigned a vote of straight to finalization, it went through very fast (probably it didn't but was a mistake)

I then went to refresh my "home" section and got a "we are sorry something went wrong" message. I clicked on the back button on my browser which somehow appeared to log me out. I tried to sign in again. I was met with the same "we are sorry something went wrong" message. I have now clicked papyri.info away and disconnected my chrome browser to write this issue. I shall try to sign in again soon and let you know whether it worked

**Comment by jcowey** [comment]
OK. Signed in again. And the text went through again. 

So stay chilled, don't panic. Disconnect from the connection on the browser. Let everything cool down and wait 15 minutes. Return and find everything in working order.

What I wrote above did happen and would be disconcerting to many.

**Comment by ryanfb** [comment]
I deployed some updates this morning to try to fix/improve some of the issues we've been seeing. One of these (https://github.com/sosol/sosol/commit/75012c289017a32e2a1fb16f99808a6b6b3ef55e)  introduced a bug which I re-deployed a fix for after seeing your errors in the logs: https://github.com/sosol/sosol/commit/2c9170a865899519229be4105059565a982559bd

**Comment by jcowey** [comment]
http://papyri.info/editor/publications/70706/ddb_identifiers/159944/edit

was the file that induce what happened. I have now opened but cannot see the timestamp yet. Just fyi if that maybe helps

**Comment by jcowey** [comment]
And thanks
