### ISSUE TITLE
Meta and Text Boards for DCLP on dev not showing up

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#125]
Signed into dev.papyri.info.
when I click on boards I see: 
![bildschirmfoto 2019-01-17 um 13 32 48](https://user-images.githubusercontent.com/612992/51319194-b2c3ca80-1a5c-11e9-946e-9c04aa56de95.png)
If I then click on DCLP I see:
![bildschirmfoto 2019-01-17 um 13 34 04](https://user-images.githubusercontent.com/612992/51319294-edc5fe00-1a5c-11e9-9d4e-702975de5ef5.png)

This does not allow me to see the submissions. Obviously I cannot vote or finalize. This is not what we need.

**Comment by jcowey** [comment]
In litpap.info when I click on boards I see:

![bildschirmfoto 2019-01-17 um 13 38 52](https://user-images.githubusercontent.com/612992/51319429-501efe80-1a5d-11e9-9f13-c211cc713d68.png)

**Comment by ryanfb** [comment]
It looks like there was (for whatever reason) a DCLP **community** and associated board on Dev, with no associated identifier classes.

I think what we ultimately want is not a separate DCLP "community", but a DCLP text + meta board in the main canonical board workflow.

So I've removed the DCLP community/board and added just a board named "DCLP" that has control over DCLP Meta and Text. Any existing/previous test submissions will probably need to be redone.

There are no decrees set up for it yet, so if you can do that here James http://dev.papyri.info/editor/boards/60/edit that would be great—if not, let me know.
