### ISSUE TITLE
DCLP board on dev not showing up properly

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#127]
When I click on boards in dev.papyri.info I see

![bildschirmfoto 2019-01-17 um 21 40 20](https://user-images.githubusercontent.com/612992/51347503-8cc01980-1aa0-11e9-8727-6a87ce31b6a9.png)

Which is good.

If I now choose DCLP, I see:

![bildschirmfoto 2019-01-17 um 21 41 39](https://user-images.githubusercontent.com/612992/51347564-b8430400-1aa0-11e9-9777-08f5c84b9fd2.png)

That is not what I would like to see.

If I compare calling up the Meta and Text board in litpap.info I see

![bildschirmfoto 2019-01-17 um 21 42 51](https://user-images.githubusercontent.com/612992/51347635-f7715500-1aa0-11e9-9f97-f4514010dbd6.png)

That is what we need to see in dev.papyri.info

**Comment by jcowey** [comment]
I was able to see the entries for voting and finalizing before I crashed the Admin section. Hope that helps.

**Comment by ryanfb** [comment]
We don't (and likely won't) have the in-progress publications from litpap.info on dev.papyri.info. You/we will need to submit test publications to check the workflows. I've submitted one just now and it should show up on the DCLP board.

**Comment by jcowey** [comment]
Ah OK. I had not realised. Fine. Thanks
