### ISSUE TITLE
Create new DCLP file crashes system perhaps

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#129]
Clicked Create new DCLP file

the URL I am seeing is

http://dev.papyri.info/editor/publications/65792 

that is as we would expect. But I now have 

Service Temporarily Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Is there a link between creating new file and crashing, or is dev just not very stable.

**Comment by ryanfb** [comment]
What I saw in the logs for this crash was just an out-of-memory error. Not sure what the root cause was, but I don't believe it was this, as I was able to create a new DCLP publication with no issue after starting it back up.
