### ISSUE TITLE
Bug in DCLP Meta Preview

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#133]
In the following file
http://dev.papyri.info/editor/publications/65822/dclp_meta_identifiers/149356/edit
I can use the Meta section fine. The XML shows up fine. When I click on Preview I get an error
HTTP ERROR 500
and see
![bildschirmfoto 2019-02-07 um 15 34 24](https://user-images.githubusercontent.com/612992/52418759-0fac2100-2aef-11e9-8111-c4639505664c.png)

In comparison the same file in litpap.info gives me a preview. From
http://litpap.info/editor/publications/1736/dclp_meta_identifiers/3577/edit
if I click on Preview I get a page
![bildschirmfoto 2019-02-07 um 15 44 17](https://user-images.githubusercontent.com/612992/52418877-44b87380-2aef-11e9-8a12-53315ee19934.png)

**Comment by jcowey** [comment]
It would be great if DCLP in papyri.info would also show the Preview information.

**Comment by ryanfb** [comment]
Getting `Java::JavaxXmlTransform::TransformerConfigurationException`: "Failed to compile stylesheet. 1 error detected."

Backtrace:
```
lib/jruby_xml.rb:425→ RUBY.get_transformer
--
lib/jruby_xml.rb:306→ RUBY.apply_xsl_transform
app/models/hgv_meta_identifier.rb:20→ RUBY.preview
app/controllers/dclp_meta_identifiers_controller.rb:83→ RUBY.preview
```

**Comment by ryanfb** [comment]
See also #132.

**Comment by ryanfb** [comment]
Should be fixed now. Problem was the new metadata preview XSL (https://github.com/sosol/sosol/blob/dclp_reintegration/data/xslt/metadata/preview.xsl) uses included XSLT from the DCLP navigator fork, but I hadn't run `bundle exec cap local externals:setup` before deploying on dev. Re-deployed with this run and calling preview on this identifier now works.
