### ISSUE TITLE
DDbDP files in dev apparently not being assigned a finalizer

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#139]
On the basis of 
http://dev.papyri.info/editor/publications/65841
(two AcceptText votes pushed the file through - it was http://dev.papyri.info/editor/publications/65840)

The file is sitting in the Approved section. I went to the Overview where I was presented with a Make me finalizer button. I clicked it. 

Nothing has happened. The file is still in the Approved section. And still with a finalizer assigned and displayed.

**Comment by jcowey** [comment]
The same appears to be happening in the HGV board.
A new DDbDP file was created (completely new). http://dev.papyri.info/editor/publications/65844
Metadata was added as well as a translation.
So the file went to the HGV board where it is now sitting
http://dev.papyri.info/editor/publications/65845
Again I cannot make myself finalizer with success. No finalizer has been assigned. Although I clicked on Make me finalizer nothing has happened.

**Comment by jcowey** [comment]
By the way DCLP files have been rigorously tested and there assignment of finalizer etc and finalization itself DID work.

**Comment by jcowey** [comment]
Here is a googledoc which records our testing.

https://docs.google.com/document/d/1wQ4a3z3JmWAqGzwpjWA-ifU--iEEFbemZIv-oOCKnQY/edit

**Comment by ryanfb** [comment]
It looks like this is probably all just due to a missing object in the DDbDP board's git repo on dev only, likely due to some earlier testing issue. Currently investigating. May need to just wipe out dev and re-sync from prod, then restore the DCLP boards in MySQL.

**Comment by ryanfb** [comment]
Closing because this was fixed by cloning prod to dev a while back.
