### ISSUE TITLE
Editor slowness

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#150]
I am not sure whether it is right to be opening this issue under: 
https://github.com/papyri/sosol/issues

There has been a little improvement on functions such as saving and toggling between Leiden+, XML and Preview. Still a bit slow, but much better. Around 6/7 seconds.

Signing in still takes me 2 minutes - 120 seconds.
Opening the Biblio board has just taken 4 minutes 45 seconds - 285 seconds. 
HGV board around 60 seconds.
DDb board around 55 seconds.

**Comment by jcowey** [comment]
Opening Overview of a file in the Biblio board from the Approved section - 15 seconds.
Clicked on Make me finalizer - 
http://papyri.info/editor/publications/74382 - spinning for 4 minutes 45 seconds - 285 seconds

**Comment by jcowey** [comment]
Just wanted to put down a marker for the first time that I opened the editor after the merge with DCLP.
papyri.info sign in: 125 seconds
ddbdb board: 55 seconds
hgv board: 54 seconds
biblio board: 195 seconds
dclp board: 43 seconds

**Comment by jcowey** [comment]
16 May 2019
papyri.info sign in: 128 seconds
ddbdb board: 44 seconds
hgv board: 42 seconds
biblio board: 175 seconds
dclp board: 35 seconds

**Comment by jcowey** [comment]
17 May 2019
papyri.info sign in: 125 seconds
ddbdb board: 78 seconds
hgv board: 59 seconds
biblio board: 177 seconds
dclp board: 41 seconds

**Comment by ryanfb** [comment]
Believe this was resolved by @hcayless.
