### ISSUE TITLE
Display of HGV Meta suboptimal

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#154]
I am in the DDbDP board and having a look at eight submissions from today. They are 

![Bildschirmfoto 2019-05-15 um 18 36 12](https://user-images.githubusercontent.com/612992/57792898-6190c280-7740-11e9-9744-ce228bd37245.png)

In the case of the numbers three and four: P.Bingen 94(RuthDuttenhöfer) and O.Bankes 38 (Ruth Duttenhöfer) appear as expected in the Vote column. In the HGV Meta column I would expect to see P.Bingen 94 and O.Bankes 38 but instead see HGV Meta 78062 and HGV Meta 699511.

In the case of the top two I see the HGV Meta numbers in both the Vote column and the HGV Meta column where I would expect to see SB 18 14043 and SB 18 14046 in the relevant positions in the Vote column and the HGV Meta column 

Quite why Ch.L.A. 10 409 is as expected I am not quite sure.

**Comment by jcowey** [comment]
If you compare with the entries below the ones just mentioned you can see how it used to be.

![Bildschirmfoto 2019-05-15 um 18 24 18](https://user-images.githubusercontent.com/612992/57792748-0c54b100-7740-11e9-9769-4de3ac76142e.png)

It would be great if you could fix it so that it that aspect is as it was.

I assume the somehow the DCLP merge has created a slight problem because in DCLP it is the TM numbers which appear

**Comment by jcowey** [comment]
Would be super if you could give this priority, because only having HGV numbers means checking against Trismegistos each time and slows the process considerably.

**Comment by ryanfb** [comment]
It looks like this is an issue somewhere in the `titleize` method. Old publications won't be affected as much because the results of `titleize` are usually stored in the database, instead of constructing the title from scratch each time. Will take a look at what's broken it.

**Comment by jcowey** [comment]
Yes I was noticing that one came through as normal:

![Bildschirmfoto 2019-05-17 um 17 37 03](https://user-images.githubusercontent.com/612992/57939325-6e412200-78ca-11e9-938a-0b5c1a49233e.png)

That had been sent back last week and then resubmitted.

Others appeared with what I expect in the Publication column but with HGV Meta \d+ in the HGV Meta column.

![Bildschirmfoto 2019-05-17 um 17 36 10](https://user-images.githubusercontent.com/612992/57939641-0a6b2900-78cb-11e9-8d48-bf40bd6a7751.png)


And two appeared with apparently no HGV Meta (but it is available in master)
http://papyri.info/ddbdp/p.stras;4;277
http://papyri.info/ddbdp/p.mich;9;549

![Bildschirmfoto 2019-05-17 um 17 40 55](https://user-images.githubusercontent.com/612992/57939605-f58e9580-78ca-11e9-856b-8dc468752cb2.png)

**Comment by ryanfb** [comment]
Should be fixed by https://github.com/sosol/sosol/commit/4cfd9a4f37277ec729682b52dd794b6528a04e1f. Last two look like either an issue with the Numbers Server inferencing or how the Editor is processing the response, for which I'll open a separate issue.
