### ISSUE TITLE
Renaming went awry

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#156]
http://papyri.info/editor/publications/76796

now appears to be empty. Happened about 09.16 EST in Center for Hellenic Studies on renaming.

![Bildschirmfoto 2019-06-10 um 09 18 13](https://user-images.githubusercontent.com/612992/59198040-ca613400-8b60-11e9-9fb0-960e7b5a4d82.png)

**Comment by jcowey** [comment]
http://papyri.info/editor/publications/76839

![Bildschirmfoto 2019-06-10 um 09 58 59](https://user-images.githubusercontent.com/612992/59200616-a43e9280-8b66-11e9-8339-d54961fd0098.png)

**Comment by jcowey** [comment]
Maybe memory is exceptionally low.

I simply made a correction in the Greek text and clicked on save. It failed to save.

![Bildschirmfoto 2019-06-10 um 10 12 21](https://user-images.githubusercontent.com/612992/59201385-54f96180-8b68-11e9-8358-fbefc531b3c9.png)

**Comment by hcayless** [comment]
This is disk memory, and that'll be why it failed. I've freed some up, and
will restart, just in case

**Comment by ryanfb** [comment]
http://papyri.info/editor/publications/76796 should be recovered.

**Comment by ryanfb** [comment]
http://papyri.info/editor/publications/76839 doesn't seem to have any issues - reopen if there are!
