### ISSUE TITLE
File could not load 

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#157]
Called up `papyri.info/dclp/60866`

It would not load and gave an error message. The file is 
https://papyri.info/editorpublications/76962

This is what it looks like on the user's dashboard:

<img width="1410" alt="bildschScreenShot2019-06-14 at 12 28 20 PM" src="https://user-images.githubusercontent.com/612992/59527169-dc1c4180-8ea8-11e9-84ea-3946e03c8681.png">

Not sure what to try to do. Simply delete it.

But make sure that `papyri.info/dclp/60866` can be called up

**Comment by ryanfb** [comment]
Not sure what happened with this publication - has no identifiers and a wonky title/branch name. <http://papyri.info/dclp/60866> loads in the navigator, and if I create an editor publication from it I seem to have no issues. I deleted the wedged `https://papyri.info/editor/publications/76962` publication to resolve, as suggested.
