### ISSUE TITLE
Stuck and broken in Translations Finalization

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#161]
The following file is in the Translations Finalization section.

It cannot be properly processed

 - [x] http://papyri.info/editor/publications/50559/hgv_trans_identifiers/114744/edit

Can you please have a look and see whether you can reinstate it so that it can be processed and finalized.

Assign to http://papyri.info/editor/users/MatthiasMueller

Thanks

**Comment by ryanfb** [comment]
Looks like there was an issue with renaming. I've unwedged it and the rename should already be done.
