### ISSUE TITLE
Leiden+ needs coaxing

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#163]
In the last week or so it has been the case the when one opens a text in the editor and clicks on the Leiden+ it spins for minutes. 

The way round this is to click on preview / XML and then click back to Leiden+, which then usually opens as expected. Sounds ridiculous but has often worked.

Sometimes when working, on saving it goes into spinning mode. If one then clicks on Preview too impatiently the work can be lost, but sometimes it has been spinning enough to have got Leiden+ through but still spin.

All very odd behaviour. I have had it reported to me by at least one other user.

Would you please have a look and see whether more capacity should be assigned to Leiden+ or whatever it takes to stop the above described behaviour.

Many thanks

**Comment by jcowey** [comment]
Entering and saving in Leiden+ is becoming most irritating and off putting. Before saving I am forced now to use command A then command C before saving. If it spins I hit preview. Then Leiden+ then command A command C and then save. That usually works. 

Sometimes some of the saved stuff appears not to be saved when returning to the file.

This behavious is apparently not affecting people working in DCLP files!! 

All seems very odd

**Comment by ryanfb** [comment]
I've just restarted the XSugar servers. Apparently one had crashed with an out-of-memory error (throwing off the load-balancing), and the other was pegged at full load. I'll keep an eye on the logs to see if I notice anything, but let me know if the problem persists or not.

**Comment by jcowey** [comment]
Behaving nicely now, thank you.
