### ISSUE TITLE
Delete unnecessary Sosol identifiers

### ISSUE THREAD

**Issue by esthergarel** [papyri/sosol#172]
The following file should remain :
http://papyri.info/editor/publications/42030/ddb_identifiers/95454/edit
 
The following two files should please be deleted :
http://papyri.info/editor/publications/42030/ddb_identifiers/95455/edit
http://papyri.info/editor/publications/42030/ddb_identifiers/95456/edit

I assume once the two files are deleted, I will then be able to finalize the file.

**Comment by esthergarel** [comment]
Same problem for another file.

File to keep : 
http://papyri.info/editor/publications/48727/ddb_identifiers/110558/edit

File to delete : http://papyri.info/editor/publications/48727/ddb_identifiers/110559/edit

**Comment by ryanfb** [comment]
Should be done for both. Please make sure on the "finalize review" screen for each that only one file is being committed to the repo.
