### ISSUE TITLE
Stuck and broken in Finalization 

### ISSUE THREAD

**Issue by esthergarel** [papyri/sosol#173]
Like #143,  #158 and #168. The following file is in my Finalization section.

I can open the following file

 - [ ] http://papyri.info/editor/publications/44553

But, when I try to go to Leiden +, I get a 
"Error retrieving file content from repository. This error has been logged for review by an administrator."
message.
Can you please assign it to me :
http://papyri.info/editor/users/esthergarel

**Comment by ryanfb** [comment]
Should now be available for finalization at: http://papyri.info/editor/publications/79753
