### ISSUE TITLE
Stuck and broken in Finalization

### ISSUE THREAD

**Issue by esthergarel** [papyri/sosol#174]
I can access and make changes in the Leiden +, but can't see the comments for the following file : 
 - [x] http://papyri.info/editor/publications/54800/ddb_identifiers/124722/edit

I get the message 
"We're sorry, but something went wrong.
We've been notified about this issue and we'll take a look at it shortly.
You should be redirected momentarily."

Can you please make sure that I can access the comments and proceed to the finalization process.

**Comment by ryanfb** [comment]
It looks like there was an error with this publication where it was assigned to two finalizers - Anne Boudhors already renamed and finalized it as O.Frange 770, and the renaming caused the duplicate copy to be unable to find the comments: https://github.com/papyri/idp.data/commits/master/DDB_EpiDoc_XML/o.frange/o.frange.770.xml

As a result, I've just gone ahead and removed the duplicate copy that was in your finalizing section.
