### ISSUE TITLE
Make finalization possible

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#192]
The following file was renamed and finalization was attempted.

 - [x] http://papyri.info/editor/publications/80421

The following message was given on finalization:

> Publication has one or more identifiers which need to be renamed before finalizing: papyri.info/dclp/SoSOL;2019;0142, papyri.info/dclp/SoSOL;2019;0142

> 

Would you please either push this through the finalization process or make available so that it can be finalized by 
http://papyri.info/editor/users/Mike%20Sampson

**Comment by ryanfb** [comment]
Should now be finalizable.
