### ISSUE TITLE
Finalized did not go through

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#199]
I finalized 

 - [ ] http://papyri.info/editor/publications/85052/ddb_identifiers/193396/edit

but it did not function all the way through. The file is still in my finalization section. If I try to look at the XML or Leiden+ I just see an empty screen. 
The file must be in some sort of corrupted state. 

Would you please push it all the way through finalization (it was ready) or put it back to a state where I can finalize it again.

http://papyri.info/editor/users/james.cowey

Thanks

**Comment by jcowey** [comment]
The file made it through to master:
https://github.com/papyri/idp.data/blob/master/DDB_EpiDoc_XML/p.gascou/p.gascou.38.xml

and the resulting PN display is fine:
http://papyri.info/hgv/39337

**Comment by ryanfb** [comment]
I've manually changed the status to finalized, which should fix things.
