### ISSUE TITLE
www.papyri.info/ddbdp/p.bub;1;4 not found via PN search

### ISSUE THREAD

**Issue by rla2118** [papyri/sosol#2]
Dieter Hagedorn has brought to my attention that this papyrus does not get discovered when searching for relevant Greek words, phrases, or partial terms. Is it not in the index?

**Comment by hcayless** [comment]
Should be fixed. SB 22,15625 reprints part of P.Bub 1, 4, but we don't support partial reprint links like that, so it was putting the two together.
