### ISSUE TITLE
Finalized three times but doesn't budge

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#201]
I finalized the following file three times.

 - [ ] http://papyri.info/editor/publications/84671/finalize_review

I can still see the XML and Metadata preview etc. The news feed does not register the file as finalized. 

Would you please unstick it so that I can finalize it. Or if it is easier finalize it.

http://papyri.info/editor/users/james.cowey

Thanks

**Comment by jcowey** [comment]
This one is still not working.

**Comment by ryanfb** [comment]
Apparently this one was in a pretty inconsistent state. New, finalizable publication copy should be here, and should retain earlier changes made during finalization: http://papyri.info/editor/publications/85429/finalize_review
