### ISSUE TITLE
Observing patterns of slippage.

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#203]
Since the last big clean up by Hugh (23.4.2020) there has been NO slippage. Votes go through, make me finalizer works fine. 
Yesterday evening was the first slippage for me. The pattern was like this. I voted a text through:

http://papyri.info/editor/publications/85685/ddb_identifiers/194758/edit

The vote seemed to be quick. The file landed in finalization but without an assigned finalizer:
![Bildschirmfoto 2020-05-04 um 19 46 49](https://user-images.githubusercontent.com/612992/80996431-16375e80-8e40-11ea-8114-c829976e3ad8.png)

P. Bas. 20 is the text without a finalizer.
(I can make myself finalizer by going to the overview section and clicking on "make myself finalizer" [but I cant access this function in the final column of the editorial board]).

Unaware of the fact that the finalizer had not been assigned (it takes a few seconds anyway) I continued to vote on another text:

http://papyri.info/editor/publications/85687/ddb_identifiers/194762/edit

The vote on this file was very quick (it shouldn#t be so quick I reckon: standard is about 2 to 3 seconds, this one was almost immediate, slipping as it were). It fails of course to be picked up by the news feed and went into the waiting section where it is sitting awaiting attention, see #202.

I describe at length with examples in the hope that maybe the log will offer a clue to what happens. 
I have noticed this behaviour before. A vote is quick and fails to assign a finalizer, the next vote (straight to finailzation, as in all above mentioned cases) slips the system and does not land where it ought to.

**Comment by ryanfb** [comment]
Something that I haven't considered before, but might be worth considering: maybe we should just add a DB-level mutex lock with repo granularity on all non-read-only Git operations. Git itself **should** have such a lock internally, but maybe there's some other issue e.g. resource consumption/contention that results in these issues when a whole lot of concurrent operations are being attempted. A mutex lock would ensure that only one operation is ever modifying the repo. It may slow things down a bit, but if it winds up getting us more reliable consistency it's probably worth it.

**Comment by jcowey** [comment]
"concurrent operations" 
It has now been the case for several months that whenever I vote I try to force myself to wait a few seconds, check the news feed by refreshing my own dashboard (indicates to me that the vote has gone through) before giving the next vote. On the whole that works well. 

Often it would be quite nice to be able to vote and then vote again immediately once the previous vote has gone through. In the past I think that made me think that such swift action was counter productive and  caused more breakage / slippage. Of course I cannot give evidence for this.

**Comment by ryanfb** [comment]
We've already added mutex locks with publication granularity for a few actions to try to prevent any concurrent actions breaking things. It looks like these are: finalize, submit, become finalizer, repack canonical, and tally votes. So this would just build on that and extend it to git operations. Maybe another good candidate (in addition to "tally votes") would be votes in general.
