### ISSUE TITLE
Cannot 'open in editor' (DCLP)

### ISSUE THREAD

**Issue by samosafuz** [papyri/sosol#217]
This morning I attempted to edit a pair of related files in DCLP (TM 65628 and TM 65823) and was unable to open either one. I suspect that the problem is related to the fact that both texts are aggregated with a pair of Michigan APIS entries (michigan.apis.1990 and michigan.apis.3413).

My suspicion is based on the web address on the error screen I received, which suggests that the system is trying to open an APIS entry first (as opposed to the DCLP record?):

![image](https://user-images.githubusercontent.com/61889129/87169794-79110000-c29e-11ea-9d79-9722d740067c.png)

The fact that there are two APIS entries to choose from may be part of the problem (there is no APIS identifier at all in the address on the error screen). But when I tested this hypothesis by opening another item in DCLP with multiple APIS entries aggregated (i.e., berkeley.apis.376), the publication was successfully created.

![image](https://user-images.githubusercontent.com/61889129/87170997-191b5900-c2a0-11ea-8741-e9b51c00bad9.png)

Maybe the fact that the Berkeley papyrus also exists in DDbDP has prevented the same error. But I'm not sure what has gone wrong. 

Vestiges of the error appear now in my user dashboard.

![image](https://user-images.githubusercontent.com/61889129/87169025-5cc09380-c29d-11ea-99ca-2b9ce3ea4a71.png)

I find this odd because I've attempted to open both TM 65628 and 65823 a few times for the sake of confirming the error and writing the ticket, yet there's only this one item on my dashboard. FWIW, clicking on the item under publication navigates to http://papyri.info/editor/publications/89369, with the following error screen.

![image](https://user-images.githubusercontent.com/61889129/87169146-8c6f9b80-c29d-11ea-93ad-c9a162b43da2.png)

Since I'm preparing a substantial pull request which will update the idnos in APIS records to assist in DCLP aggregation, the potential for some sort of glitch involving APIS and DCLP is of particular concern.

**Comment by samosafuz** [comment]
The same issue happened to Paul van der Laan when attempting to open TM 60866 in editor. That file has a Columbia APIS entry, too (columbia.apis.p367).

**Comment by samosafuz** [comment]
Paul van der Laan reports the same issue when attempting to open TM 60610 (yale.apis.0010620000) and TM 60862 (= columbia.apis.p363) in editor. There does seem to be an issue for DCLP items with APIS entries.

**Comment by jcowey** [comment]
Out of curiosity I navigated to http://papyri.info/dclp/60866. I then hit open in editor. I got the "We are sorry, but something went wrong notice." What I found interesting is that my news feed reported:
`You started editing papyri.info/apis (28 minutes ago)`
That would seem to indicate to me that neither the identifier of the APIS record nor that of the DCLP record is not being picked up at all, when "open in editor" is clicked.
Normally in DCLP the news feed will say:
`C. Michael Sampson started editing 64796 (about 7 hours ago)`
Where 64796 indicates the DCLP identifier. 
Is the number server somehow not properly jigged to take DCLP identifier in conjunction with an APIS identifier?

**Comment by ryanfb** [comment]
Yes, this looks to be an issue with how the papyrological navigator is linking to the editor. I'll continue looking into it, but in the meantime a workaround is to use the editor's "Advanced Create" and paste the identifier e.g. `papyri.info/apis/yale.apis.0010620000` into the PN ID field in the "From PN ID" section, which works for me with the examples above.

**Comment by ryanfb** [comment]
It looks like the issue was that for DCLP+APIS cases, the link was made from a DCLP context trying to use the `apisid` `idno`, which isn't in the DCLP record. I've pushed a fix which should use the DCLP identifiers instead, which should resolve this issue.

@hcayless: If you can pull the latest `navigator` with this change, I think re-indexing (or whichever process generates the HTML output) should resolve this issue on production.
