### ISSUE TITLE
Finalize file

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#230]
Amongst one of the files which has been around for months and years there is this one:

 - [x] http://papyri.info/editor/publications/37101/ddb_identifiers/84057/edit

Nick Gonis wrote the following to me: "I resurrected SB 20 14427 (berkes.lajos), a very old submission of a broken file first submitted by Georg Schmelz. I've made numerous changes needed and  finalized three times, but they system won't commit it. "

Would you please push it through, i.e. finalize it yourself so that it leaves the Approved section and is visible in papyri.info.

Thanks

**Comment by ryanfb** [comment]
Manually restored with commit: https://github.com/papyri/idp.data/commit/a6a3296e0d99e0f10182d6b58010a8d22cc6fb0b

Changed publication status in the Editor to reflect finalization.
