### ISSUE TITLE
On submission, failure

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#235]
When submitted this file 

 - [x] http://papyri.info/editor/publications/93198

from the user

http://papyri.info/editor/users/simoeis

failed to make it to the DDB editorial board.

Furthermore the file in his "Editing" section is broken. The XML is empty.

Would you please reinstate the Leiden+/XML so that the file can be submitted again. Or reinstate and submit to the board, whichever is easier.

Thank you.

**Comment by ryanfb** [comment]
Should be reinstated for submission. Let me know if there are any issues and I'll manually walk it through the submit if so.
