### ISSUE TITLE
Only partially finalized: unusual one

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#247]
15 november 2020. Editor slow and error prone. I "finalized" a file:

 - [ ] https://papyri.info/editor/publications/93795/ddb_identifiers/214225/edit

Various commits connected with this finalization seem to have gone through as expected:
https://github.com/papyri/idp.data/commit/dfa2cfec6e999222336b6d89be3c4bfecba9628a
https://github.com/papyri/idp.data/commit/1b97986a4153897118ae815f7d1f56ed49f5ff2a
The following looks OK:
https://github.com/papyri/idp.data/commit/a61fe82df2521f8a5c76be24144d5d4b92995f2b
but at 
https://github.com/papyri/idp.data/tree/master/DDB_EpiDoc_XML/p.daris
there is no
p.daris.15.xml

https://github.com/papyri/idp.data/commit/2133e3b39a75c972d484e75ebcb39be7485372fd
also seems fine.

https://papyri.info/editor/publications/93795/ddb_identifiers/214225/edit 
is still in my finalize section. 

Would you please push it through properly so that a
p.daris.15.xml exists and
http://papyri.info/ddbdp/p.daris;;15
displays metadata and text.

Many thanks

**Comment by ryanfb** [comment]
It looks like there was an issue with the treewalking process during finalization merge, so all the commits are there but the final merged tree wasn't correct:
```
Recovering branch: DDbDP_Editorial_Board/committed/2020/11/15/SB_18_14020 -> DDbDP_Editorial_Board/2020/11/14/ngonis/2020/11/13/SB_18_14020
  Identifier Load (460.1ms)  SELECT `identifiers`.* FROM `identifiers` WHERE `identifiers`.`publication_id` = 93795
JGIT TREEWALK for DDB_EpiDoc_XML/p.daris/p.daris.15.xml on DDbDP_Editorial_Board/committed/2020/11/15/SB_18_14020: org.eclipse.jgit.treewalk.TreeWalk@46a9c368
Unable to retrieve DDB_EpiDoc_XML/p.daris/p.daris.15.xml in branch DDbDP_Editorial_Board/committed/2020/11/15/SB_18_14020
Please check/recover branch manually.
```
Since the commits/blobs were there, I restored the content from the commit before finalization merge and set the publication to be finalized.

**Comment by jcowey** [comment]
It does not really matter, as the text is relatively insignificant, but the editorial history got lost.
