### ISSUE TITLE
content disappeared + renaming not possible

### ISSUE THREAD

**Issue by mariusgerhardt** [papyri/sosol#251]
concerning http://papyri.info/editor/publications/94218/hgv_trans_identifiers/215294/edit
I was about to finalise this translation and the system told me that there are too many identifiers for this publication, which need to be renamed, i.e. papyri.info/hgvtrans/SoSOL;2011;0170 should be renamed to papyri.info/hgvtrans/91681
Furthermore, when trying to open this translation in order to write this ticket I realized that the content disappeared (it was there last week).

**Comment by ryanfb** [comment]
Should now be fixed and ready for finalization. There was a database error during the rename which left the publication in an inconsistent state. The rename has already taken place, I've just brought the database in line with it.

**Comment by mariusgerhardt** [comment]
Thank you very much. Content reappeared, renaming had already taken place. I have tried to finalize this record, but it remains in the translations-board. Somehow, it got stuck there and the finalization is not succesfull.
