### ISSUE TITLE
Finalization not possible

### ISSUE THREAD

**Issue by mariusgerhardt** [papyri/sosol#252]
concerning http://papyri.info/editor/publications/94218/hgv_trans_identifiers/215294/edit
and issue #251
Thank you very much. Content reappeared, renaming had already taken place. I have tried to finalize this record, but it remains in the translations-board. Somehow, it got stuck there and the finalization is not succesfull.

**Comment by ryanfb** [comment]
There were some git issues with this one, but I believe it should now be finalized. Should show up on next sync at https://github.com/papyri/idp.data/blob/master/HGV_trans_EpiDoc/91681.xml.
