### ISSUE TITLE
Failed rename leads to broken file (DCLP)

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#257]
This concerns two files in the DCLP Finalize section: 

 - [ ] https://papyri.info/editor/publications/92483/dclp_text_identifiers/210928/edit
 - [ ] https://papyri.info/editor/publications/88019/dclp_text_identifiers/200202/edit

Would you please walk each file back to the stage it was at before the rename was carried out. That should allow me to work on them again.

As an aside it seems that renaming by adding a letter suffix to the TM number does not work in DCLP (I had assumed that it would). It is, with the benefit of hindsight, probably good that it is not possible in DCLP (it has to remain possible in HGV / DDbDP).

Can you please assign them to me

http://papyri.info/editor/users/james.cowey

Thanks.

**Comment by ryanfb** [comment]
I don't know that this was an intentional restriction, just that it triggered an unexpected error, which should now be fixed with e.g.: https://github.com/sosol/sosol/commit/2c855af624f6cefe6c02365d228e9d552fd07f19

Both of these should now load with their existing renames.

**Comment by jcowey** [comment]
https://papyri.info/editor/publications/92483/ : went to https://papyri.info/dclp/100001, which has now been merged with https://papyri.info/dclp/65682
