### ISSUE TITLE
Create New DCLP Publication throws error

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#259]
https://papyri.info/editor/publications/advanced_create

when I click on 

Create New DCLP Publication

I get a 

![Bildschirmfoto 2021-01-12 um 15 24 59](https://user-images.githubusercontent.com/612992/104326787-66e07a80-54ea-11eb-8bc3-9fd1ceea66cc.png)

error.

This should be fixed

**Comment by ryanfb** [comment]
This should now be fixed in production.
