### ISSUE TITLE
File transfer failed

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#262]
With 
https://github.com/papyri/idp.data/commit/e72c735b46e8716d5d7e1eee5772414771f849e3
and
https://github.com/papyri/idp.data/commit/9dfb217f9ddf6be68d5e9a137d5ac67d2ee98a6e
I committed an HGV file. It is now displayed as
http://papyri.info/hgv/704791
What should have happened next is that the file is pushed across to the DDB editorial board to allow
voting, correcton and finalization of the DDB text of the publication. This did not happen.
https://papyri.info/editor/publications/78970
went back to the Approved section of HGV board.

Would you please do the necessary to make it appear on the DDB board so that I can go ahead 
and process it.

 - [x] https://papyri.info/editor/publications/78970

Can you please assign it to me

http://papyri.info/editor/users/james.cowey

Thanks.

**Comment by ryanfb** [comment]
Should now be on DDB for voting at: https://papyri.info/editor/publications/97097
