### ISSUE TITLE
Cannot rename this one and now broken

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#265]
This got caught in some editor crash / restart problems, as I tried to make myself finalizer. On re-opening the editor I had to go and make myself finalizer again. That worked and I find it in my finalize section. Tried renaming and get the mesage the the SoSOL filename was not recognised.

 - [ ] https://papyri.info/editor/publications/97103/ddb_identifiers/222464/edit

now getting this

"Error retrieving file content from repository. This error has been logged for review by an administrator."

Would you please re-instate content again.

**Comment by ryanfb** [comment]
It looks like the rename to `papyri.info/ddbdp/apf;63;120` had already taken place in Git, but the database identifier rename got rolled back. I've redone the database rename so they should now be in sync and the publication should be finalizable.
