### ISSUE TITLE
Create New DCLP Publication: broken

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#270]
If a user goes to 
https://papyri.info/editor/publications/advanced_create
and clicks on 
Create New DCLP Publication

the following error message appears:

![Bildschirmfoto 2021-03-01 um 15 28 26](https://user-images.githubusercontent.com/612992/109510891-cf87b480-7aa2-11eb-9cd1-d8e5a0f058b8.png)

I thought we had checked all the advanced create functions, but this seems to have slipped through.

Would you please fix it as soon as you can manage.

**Comment by ryanfb** [comment]
Thanks for letting me know, should now be fixed on production.
