### ISSUE TITLE
Cannot open DCLP Meta

### ISSUE THREAD

**Issue by samosafuz** [papyri/sosol#274]
As I was preparing to finalize [TM 65908](https://papyri.info/editor/publications/97628) tonight, I encountered a problem which has subsequently recurred with other files. 

Although I was able to access and make corrections to the file via the [DCLP Text](https://papyri.info/editor/publications/97628/dclp_text_identifiers/223706/edit) tab, every attempt I made to access and update [DCLP Meta](https://papyri.info/editor/publications/97628/dclp_meta_identifiers/223705/edit) bounced me to the "We're sorry, but something went wrong" card.

Further attempts to access the metadata of other files on the DCLP Board produced varying results. Sometimes I encountered the same problem (e.g., [here](https://papyri.info/editor/publications/97619/dclp_meta_identifiers/223686/edit), and [here](https://papyri.info/editor/publications/97611/dclp_meta_identifiers/223670/edit)) but sometimes the metadata opened up just fine (e.g., [here](https://papyri.info/editor/publications/97458/dclp_meta_identifiers/223327/edit) and [here](https://papyri.info/editor/publications/96774/dclp_meta_identifiers/221734/edit)).

Obviously, this will impact my editorial activity on the DCLP board, and it'd be nice to have it sorted out.

**Comment by samosafuz** [comment]
This issue also appears to be affecting my ability to work with DCLP metadata more broadly. I have [TM 65906](https://papyri.info/editor/publications/97729/dclp_meta_identifiers/223959) open for editing, and although I can navigate to the metadata mask of this file, as soon as I click on 'save entire file' I get the "We're sorry" card.

**Comment by ryanfb** [comment]
Thanks, this is related to the Rails 5 upgrade which was recently deployed (sosol/sosol#278). I'm going to start working through the list of current error reports and batch some fixes together for a re-deploy, and will post again here when I think some of the DCLP meta issues should be resolved.

**Comment by ryanfb** [comment]
I believe this should be fixed for both viewing and saving now. If there's still issues with DCLP meta, please feel free to reopen this issue.

**Comment by samosafuz** [comment]
Alas, it's still behaving oddly. I can now access [DCLP meta](https://papyri.info/editor/publications/97628/dclp_meta_identifiers/223705/edit), but when I make changes and attempt to save, the changes I entered are disappearing, leaving blank fields. Something's still amiss with saving.

<img width="630" alt="Screen Shot 2021-03-12 at 10 50 42 AM" src="https://user-images.githubusercontent.com/61889129/110964292-09697e00-8321-11eb-9b11-d41220163885.png">

**Comment by ryanfb** [comment]
Thanks again—should now be fixed in production.

**Comment by samosafuz** [comment]
Thank you; I can't imagine this has been fun to wrangle. 

Two things have come to light after a quick review.  One is the 'Online resources' field: for [TM 65908](https://papyri.info/editor/publications/97628/dclp_meta_identifiers/223705/edit) I've tried to save the [relevant page](http://163.1.169.40/cgi-bin/library?e=q-000-00---0POxy--00-0-0--0prompt-10---4------0-1l--1-en-50---20-about-4510--00031-001-0-0utfZz-8-00&a=d&c=POxy&cl=search&d=HASHde178c021c818dbb2607f4) in the P.Oxy catalogue, the [image file](http://163.1.169.40/gsdl/collect/POxy/index/assoc/HASHde17/8c021c81.dir/POxy.v0066.n4510.a.01.hires.jpg) accessed via that catalogue, and even the [P.Oxy. homepage](http://www.papyrology.ox.ac.uk/POxy/), with no success. After saving, the field comes up empty. Even the usual trick of adding an additional, blank field before saving did not solve the problem.

The other is provenance, which was wiped clean when things broke earlier on. I've been able to reenter and save provenance information, which is appearing as `placeName` in the xml, but that information is not being passed to `origPlace` as it used to: my `origPlace` is populated only with the `<provenance type=""/>` value: Fundort: ; Shreibort: ; i.e., `type="Found"` and `type=:Written`.

**Comment by ryanfb** [comment]
The provenance component of this should now be fixed for DCLP as well. I'll start work on the "online resources" field next.

**Comment by ryanfb** [comment]
Both of these problems should now be fixed for DCLP on production.
