### ISSUE TITLE
Commentary section does not function as expected.

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#275]
I have noticed a little bug.

I cannot write a commentary or introductory matter. Open a file in Leiden+ (under the Text button) and then click on 
commentary (in both DDB and DCLP)

I have attached a screenshot of what I get. 

![Bildschirmfoto 2021-03-12 um 13 28 48](https://user-images.githubusercontent.com/612992/111197936-57031680-85bf-11eb-8f79-50db401b4812.png)

Would you please do the necessary to bring that back as soon as you can.

**Comment by ryanfb** [comment]
Should now be fixed for both DCLP and DDbDP on production.

**Comment by jcowey** [comment]
Many thanks. Tested and it worked. Great.
