### ISSUE TITLE
Preview of provenance in HGV broken

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#276]
In the provenance section of metadata the preview of provenance does not function as expected. This affects both HGV and DCLP files.
This is not just a matter of not seeing the preview. It also means that content it not written to <origPlace>
If you look at 
https://github.com/papyri/idp.data/blob/master/HGV_meta_EpiDoc/HGV100/99302.xml#L32
and then 
https://github.com/papyri/idp.data/blob/master/HGV_meta_EpiDoc/HGV100/99302.xml#L32
you will see that the provenance is presented in two manners. 

Sitting on the HGV board at present are two files:
https://papyri.info/editor/publications/97835/hgv_meta_identifiers/224168/edit
and
https://papyri.info/editor/publications/97834/hgv_meta_identifiers/224165/edit
If you look at the XML there you will find the provenance portions which match
https://github.com/papyri/idp.data/blob/master/HGV_meta_EpiDoc/HGV100/99302.xml#L32

but there is no origPlace entry.

If you go to the HGV mask you will see the provenance fields filled but no preview.
If you click on update geo preview nothing happens.

Would you please do the necessary to fix this as soon as you can.

Thanks 

James

**Comment by jcowey** [comment]
I notice this is the same as observed by Mike Sampson in #274. last comment

**Comment by ryanfb** [comment]
NB: the *preview* should now be fixed on production, and I'm now working on fixing the actual updating of the `<origPlace>` element when the file is saved.

**Comment by ryanfb** [comment]
Updating provenance should now be fixed for HGV on production (correctly updates `<origPlace>`).
