### ISSUE TITLE
Admin bugs

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#281]
Not sure whether this is a sosol issue, but anyway. 

I wanted to add someone to the Translations board, so I went to Admin. Fine. Clicked on Edit boards, still fine.
clicked on add member and got a 404 we are sorry.

I then checked that on DDB board. The same error message. 

So I suspect that it is the same for all boards for me (and presumably others who would like to add board members).

Would you please have a look and fix that as soon as you can manage.

Thanks

**Comment by ryanfb** [comment]
Thanks for letting me know, I'll look into this—this is likely just a routing change in the Rails upgrade that doesn't get caught by the existing automated tests.

**Comment by ryanfb** [comment]
Should now be fixed on production (by 846d37910708ef82f80bab82e0398ce96846c7be + 5cc7dec70aa4b404c43a644e2550b7bad94c86a7).
