### ISSUE TITLE
Three more to remove from finalization section

### ISSUE THREAD

**Issue by wgclaytor** [papyri/sosol#283]
- [x] https://papyri.info/editor/publications/44967#
- [ ] https://papyri.info/editor/publications/50027#
- [ ] https://papyri.info/editor/publications/42214#

are stuck in

https://papyri.info/editor/users/gclaytor

finalize section.

These files have long since been finalized. Would you please remove them from my dashboard? Thanks!

**Comment by ryanfb** [comment]
For the two remaining, I see copies on the Translations board that are in voting status. The finalizing copies on DDB have "finalized" status. 44967 also has a translation on the translations board in voting but the finalizing copy from DDB was still in "finalizing" status, which I changed to "finalized".

**Comment by jcowey** [comment]
Ah yes I forgot about that possibility.
