### ISSUE TITLE
TM 91948 stuck in PE

### ISSUE THREAD

**Issue by rla2118** [papyri/sosol#284]
This file is stuck in finalization.

www.papyri.info/editor/publications/101543/

I'd hoped to show the committed version of it to my students tomorrow (10 June 2021). Is there any way to dislodge it by then?

**Comment by jcowey** [comment]
I suspect that there is some bug which is affecting the creation and saving of new DCLP files.
A student has just got in touch with me saying he cannot work on his DCLP file (created completely afresh)
https://papyri.info/editor/publications/101273

I myself went to Advanced create, create new DCLP publication. Changed the field Display name from Desccription of Document to Horoscope and hit save. 
I immediately got the "We are sorry message"

This makes me think that there must be a bug in the system which is affecting DCLP saving. (Fortunately DDB and HGV do not seem to be affected)

**Comment by ryanfb** [comment]
Saving DCLP works fine for me after cycling the editor, and I don't see any errors logged since then. @rla2118 does all look ok now to you?

**Comment by ryanfb** [comment]
Closing as this should now be actually fixed on production by 2a12ace. Please reopen if there are still problems.
