### ISSUE TITLE
Serious (?) Bug (?) in Leiden+ saving in DDB

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#286]
Student in Athens opened
http://papyri.info/ddbdp/p.oxy;3;496
in the editor. (He wanted to make changes and got an error message. We had a call and I got him to save the file WITHOUT any correction simply by hitting save. He got the error message appended)

![Στιγμιότυπο οθόνης (18)](https://user-images.githubusercontent.com/612992/121710482-f3af5480-cad9-11eb-8922-1f18d50cf814.png)

His publications number is 
https://papyri.info/editor/publications/101323

Leiden+ is very slow at present anyway. Hugh rebooted a few minutes ago while I was in conversation with the student in Athens. 
He tried saving again and got the same error. 

I am wondering whether this is a bug related to the problems there were on Wednesday with DCLP files
#285 

The error message is not one I am used to seeing:
"Error parsing Leiden+ at line 0, column 0. This file was not saved.

By the way I copied the file from 
https://github.com/papyri/idp.data/blob/master/DDB_EpiDoc_XML/p.oxy/p.oxy.3/p.oxy.3.496.xml
shoved it in oXygen and it validated without a murmur.

**Comment by ryanfb** [comment]
I see the same behavior for this file, but I think it's something specific in this particular file that's causing the Leiden+-to-XML conversion direction to trigger an OutOfMemory error in XSugar. Other texts are currently working as expected.

Likely something is causing the Leiden+ parse tree to consume too much memory, I'll see if I can try to isolate it down to a specific feature of this document.

**Comment by hcayless** [comment]
It has very long lines, so I’m guessing the normal splitting up of files by line isn’t helping.

**Comment by ryanfb** [comment]
- each individual line: fine
- lines 1-8: fine
- lines 9-16: fine
- lines 1-14: fine
- lines 1-15: breaks

It's currently getting processed as a single chunk, because the lines are under the default split threshold of 20. I'm going to try dropping the split threshold to 10 to see how that works.

**Comment by ryanfb** [comment]
Seems to work fine now after deploying https://github.com/papyri/xsugar/commit/4c67cef679911c114ca30242db1b92d074511a59. Hopefully the more aggressive splitting doesn't cause some other unforeseen error, but I suspect that overall it should improve XSugar performance…
