### ISSUE TITLE
Two texts wrongly merged

### ISSUE THREAD

**Issue by wgclaytor** [papyri/sosol#287]
From PN user Lavinia Ferretti: "[W.Chr. 233](https://papyri.info/ddbdp/chr.wilck;;233) and P.Tebt. I 29 wrongly merged on papyri.info. The problem comes from the DDB .xml of P.Tebt. I 30, which was not reprinted from M.Chr. 24. This xml is not accessible via the PE, can you correct it? Thanks!"

**Comment by samosafuz** [comment]
Fixed by [#249](https://github.com/papyri/idp.data/pull/249): Graham, you can close this issue.
