### ISSUE TITLE
Finalization did not perform properly

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#291]
Like #269.

I finalized the following file twice, but the finalization process does not seem to have been carried out properly.

 - [ ] https://papyri.info/editor/publications/95915

You can see the comments here:

![Bildschirmfoto 2021-07-08 um 16 34 44](https://user-images.githubusercontent.com/612992/124940698-7c9eaa80-e00a-11eb-8fad-81b00d708838.png)

There you can see the two finalizations. The news feed did not register a finalization either.
The file is completely finished and all that needs to happen is a successful finalization.
That would then push through the text file for voting and finalization.

Would you please push it through finalization.

(This file was already corrupt at a previous stage)

**Comment by jcowey** [comment]
Same with this one:

 - [ ] https://papyri.info/editor/publications/95887

**Comment by ryanfb** [comment]
First one has some inconsistent Git branches that will have to be untangled.

**Comment by jcowey** [comment]
Pushed through to #309
