### ISSUE TITLE
Unusual BUG with DDbDP board first column: "Overview" function

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#293]
This evening when I signed in to papyri.info DDbDP board

https://papyri.info/editor/user/board_dashboard?board_id=1

If I click any file in the publication column (first column) I get a "we're sorry" message.

If I click on the second column, it looks like everything is fine. 

Would you please have a look and fix the bug as soon as you can manage. It should be possible to click on the publication column and from there go to the various different parts of the file.

Means I cannot make myself finalizer by clicking in that first column (but the function remains fine by clicking on "Make me finalizer" in the third column).

**Comment by jcowey** [comment]
Not only DDbDP board phenomenon. In my own dashboard I get the same we are sorry message if I click on a file in the publication column.

**Comment by jcowey** [comment]
So it is basically a BUG with the "Overview" page. Wherever I try clicking on Overview I get the we are sorry message. One colleague here in Heidelberg confirmed the phenomenon on her dashboard. So it is not just my dashboard and boards I reckon.

**Comment by ryanfb** [comment]
This is a regression bug in the publication display template that got included in deploys I made yesterday. I will fix ASAP and close when the fix is live.

**Comment by ryanfb** [comment]
Should now be fixed on production.
