### ISSUE TITLE
"we are sorry ..." on voting in DDB board. Serious BUG.

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#294]
Voted on 

https://papyri.info/editor/publications/103165

Got a "we are sorry ..." message.

**Comment by jcowey** [comment]
But looks like it went through anyway according to the News Feed

![Bildschirmfoto 2021-07-13 um 14 18 49](https://user-images.githubusercontent.com/612992/125450296-d3b49833-e2b8-432d-bce8-7e37b25f9ac2.png)

Where one can also see that Finalization is working.

**Comment by jcowey** [comment]
Same behaviour on voting in the HGV board: 

https://papyri.info/editor/publications/101864

gave me a "we are sorry ..." message, but apparently went through.

**Comment by jcowey** [comment]
When one browses in DDB finds a text and then clicks on "Open in editor" the "we are sorry ..." message comes.

Again the actual function does happen. The file is available in my "Home Editing" section.

**Comment by ryanfb** [comment]
This is likely because after voting you would normally get redirected to the publication overview page, so this is likely a duplicate of #293.

**Comment by ryanfb** [comment]
Should now be fixed on production by the fix for #293.
