### ISSUE TITLE
Bug when saving Leiden+

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#296]
As of yesterday evening Thursday 5 August (first noticed around 23.00) saving in Leiden+ is not possible. 

This is the error message I get:

![Bildschirmfoto 2021-08-06 um 12 02 36](https://user-images.githubusercontent.com/612992/128494251-46797100-3f53-4657-ac08-2343fa45fc96.png)

or including what I entered:

![Bildschirmfoto 2021-08-06 um 12 02 18](https://user-images.githubusercontent.com/612992/128494299-dc381349-96fd-4e84-9be0-f7bc9979ede9.png)

If I go to XML I find that nothing is visisble there. If however I write XML and save it the system accepts. Preview works. I can then go to Leiden+ and see the Leiden+ rendering of what I entered in XML. If I try to save in Leiden+ I get the same message. When I then re-check the XML I see that nothing has changed and that if I click on save in XML then it is fine.

**Comment by jcowey** [comment]
This is serious for users, who want to enter Leiden+, because they cannot do so. Please would you try to fix this as soon as you can possibly manage.

**Comment by jcowey** [comment]
Have just received a mail from someone, who is having similar problems. So it does seem to be a problem that will affect all users.

**Comment by ryanfb** [comment]
Thanks for bringing this to my attention. Looks like it was caused by trying to add more-explicit SSL support to the interface XSugar uses. I've reverted that change here which seems to have fixed the problem: https://github.com/papyri/xsugar/commit/cebc77094ce7e5656f697d22d308afa3336dbee6
