### ISSUE TITLE
Delete empty and obsolete user accounts

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#297]
Please delete from the system the following user accounts:

https://papyri.info/editor/users/Georg%20Schmelz#

https://papyri.info/editor/users/georg.schmelz

https://papyri.info/editor/users/GSGS

They are empty and will no longer be used. They were all created by Georg Schmelz. I know him well and know that he is no longer contributing to papyri.info. They clutter up the 

https://papyri.info/editor/all_users_links

page. I assume that simply removing them should not have any repercussions and is easy to do. If there are difficulties then this is obviously not essential. (I can never remember which account is the one with many activities, which occasionally I like to refer to)

Moreover he used a different account 
https://papyri.info/editor/users/Georg

which shows all his work and should of course remain in existence.

**Comment by ryanfb** [comment]
Done
