### ISSUE TITLE
Submission BUG

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#299]
I have had messages from two users who on submission of a file from the editor got the message:

We're sorry, but something went wrong.
We've been notified about this issue and we'll take a look at it shortly.

You should be redirected momentarily.

I wrote to papylist to ask users not to submit until this bug is fixed.
Would you please have a look at fixing this as soon as you can manage.

**Comment by ryanfb** [comment]
Didn't mean to close from commit message, will update here when this is in production and testable.

**Comment by ryanfb** [comment]
This should now be resolved in production. Tested with a submission just now, which worked (withdrawn after).
