### ISSUE TITLE
Preview in DDB and DCLP failing

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#306]
When trying to look at DDB text or DCLP text in Preview one receives a
we are sorry error message

![Bildschirmfoto 2021-11-30 um 22 03 20](https://user-images.githubusercontent.com/612992/144127779-68cd106b-73ac-4e94-9ff4-e24c997e3392.png)

I think it is just today that this has appeared.

Can you please try to fix this as soon as you can possibly manage. It is obviously a big hindrance to entry and processing.

many thanks

**Comment by ryanfb** [comment]
@hcayless - looks like this XSLT change may have broken things editor-side? OK to revert while we try to resolve what's blocking the new version? https://github.com/sosol/sosol/commit/3d8e60644a7fd5704fc1f4a4b6b5363497472e24

**Comment by hcayless** [comment]
Yeah, of course. I'd love to know what's not working though, as it's been working on the PN side for ages...How do I access the SoSOL logs nowadays?

**Comment by ryanfb** [comment]
Error logging is at https://errbit-dc3.herokuapp.com/, live production logs are at `/srv/data/papyri.info/sosol/editor/log/production.log`
