### ISSUE TITLE
Create new translation not working: BUG

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#307]
This was reported about an hour ago by a user to me. I could replicate it.
I started with

https://papyri.info/editor/publications/107020

I clicked on Create New Translation.

That returns a "we are sorry" error message. BUT
https://papyri.info/editor/publications/107020/hgv_trans_identifiers/247759/edit

does exist (SoSOL 2021 123)

![Bildschirmfoto 2021-12-01 um 14 22 39](https://user-images.githubusercontent.com/612992/144242050-50ff6cf8-7af2-4670-a160-5a8643155cba.png)

If, however, I click on that column from my home dashboard (clicking on SoSOL 2021 123 in the "Translation column")

I also get a "we are sorry" error message for Leiden+ and Preview BUT

https://papyri.info/editor/publications/107020/hgv_trans_identifiers/247759/editxml

opens

Where I can indeed enter and save text.

**Comment by jcowey** [comment]
Hoping that if you revert the code as asked in #306, then both #306 and #307 will no longer be problematic.

**Comment by ryanfb** [comment]
I think so as well - I'm going to go ahead and push the revert, get it deployed, and split that change into a pull request so that I can figure out what we need to do to switch back to upstream XSLT.

**Comment by ryanfb** [comment]
Fixed by revert.
