### ISSUE TITLE
Advanced Create > biblio crashing

### ISSUE THREAD

**Issue by samosafuz** [papyri/sosol#313]
I'm attempting to complete a new bibliography file from Advanced Create:

[https://papyri.info/editor/publications/112370/biblio_identifiers/257455/edit](https://papyri.info/editor/publications/112370/biblio_identifiers/257455/edit)

Unfortunately, I'm getting the 'We're sorry, but something went wrong' screen whenever I try to save changes to the series title/number fields or any of the page/preface fields.

I was able to complete a previous entry by editing the .xml manually, but it would obviously be preferable to have the fields in the metadata mask functioning properly.

**Comment by jcowey** [comment]
Knock on from number servers. Or rails.

**Comment by ryanfb** [comment]
I had misappraised the issue when I was talking on Zoom with James—I think this is related to changes in REXML, the Ruby built-in XML parsing library, between Ruby version upgrades. This should now be fixed on production, please reopen if you still encounter issues.
