### ISSUE TITLE
Cannot save changes to DCLP meta before finalization

### ISSUE THREAD

**Issue by samosafuz** [papyri/sosol#320]
This morning I approved [https://papyri.info/editor/publications/114005](https://papyri.info/editor/publications/114005) on the DCLP board and set about revising it for finalization. I was able to modify the text and save my changes without any errors, but I cannot do the same with the DCLP meta: [https://papyri.info/editor/publications/114005/dclp_meta_identifiers/261381/edit](https://papyri.info/editor/publications/114005/dclp_meta_identifiers/261381/edit). Whenever I modify any of the fields and attempt to save, it flashes the "We're sorry" card.

**Comment by jcowey** [comment]
Wonder whether this is in some way similar to #313, where it was "related to changes in REXML, the Ruby built-in XML parsing library, between Ruby version upgrades"

I now note that Biblio is also not functioning properly. When I added an ISBN number I got the 404 error message. #321

**Comment by ryanfb** [comment]
I believe this should be fixed by: https://github.com/sosol/sosol/commit/3f36201e8733ad8560826e39c5658b0a7d49ed52

This is now in production so please let me know if you're still running into issues.

**Comment by samosafuz** [comment]
I tested this out last night and again this morning, and things mostly appear ok. But it looks as though there's another bug with author/work stable identifiers: they have been wiped from the records I'm revising. They do not save when entered into the metadata mask, and although I can add them manually to the xml, if I make any further changes to the metadata and save, they get erased again.

<img width="422" alt="Screen Shot 2022-05-03 at 8 45 44 AM" src="https://user-images.githubusercontent.com/61889129/166414182-1066a7df-5b0e-46bb-aae3-fe0f00d89617.png">
