### ISSUE TITLE
Saving changes for some fields of Biblio throwing 404 error messages.

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#321]
Is this somehow related to #320, in which behaviour is reported today that is new. Biblio had been fixed with #313, but is now acting up again. When I entered a ISBN number I got a 404 error message.

**Comment by ryanfb** [comment]
I believe this should be fixed by https://github.com/sosol/sosol/commit/fdf2c8407ef8a42a5cb64ee840c5536761fa06c8 which is now in production. I'll try to see what I get myself now as well.

**Comment by ryanfb** [comment]
Just tested myself with ISBN, which seems to work now. Please reopen if you're still seeing issues.
