### ISSUE TITLE
Metadata failing to appear when file is opened in the editor

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#344]
Starting here: https://papyri.info/ddbdp/bgu;14;2371

Open in editor and this is what I see:

<img width="1636" alt="Screenshot 2023-07-14 at 11 32 28" src="https://github.com/papyri/sosol/assets/612992/f398d2bc-9310-4f48-ba63-222ddf562f67">

I can edit text but not the metadata. The metadata is not being pulled up and made available (it does exist: https://github.com/papyri/idp.data/blob/master/HGV_meta_EpiDoc/HGV4/3991.xml).

The user is even being offfered the possibility of creating new metadata. 

I have tested on about 5 files and this seems to be a big problem, which affects many files but not all (see in note below). 

Can you please fix it as soon as is possible.

**Comment by jcowey** [comment]
bgu volumes seem to be affected. sb volumes seem to be OK

o.medin.madi volumes are affected.

**Comment by jcowey** [comment]
In the case of affected files when in the editor the links to the existing files in the navigator do not work. 

An example is https://papyri.info/editor/publications/128089

DDbDP Text - Identifier papyri.info/ddbdp/cpr;15;15 ([View in PN](http://papyri.info/ddbdp/cpr;15;15)): works

HGV Meta - Identifier papyri.info/hgv/9902 ([View in PN](http://papyri.info/hgv/9902)): fails

**Comment by hcayless** [comment]
I have reloaded the Numbers Server and I believe this issue is fixed.
