### ISSUE TITLE
Files not properly processed: Files stuck in submitting process

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#35]
- [x] http://www.papyri.info/editor/publications/51396/submit
 - [x] http://www.papyri.info/editor/publications/51398/submit
 - [x] http://www.papyri.info/editor/publications/51402/submit

all threw an error message when submitted:

The page you were looking for doesn't exist.

You may have mistyped the address or the page may have moved.

As far as I can see there is no trace of them on any of the boards. All three are associated with the user
http://papyri.info/editor/users/Lorelei_Vanderheyden

Can you please fix these so that they are submitted and appear on the DDB editorial board. By removing the ../submit from the URL one can see that the Leiden+ looks good etc.

**Comment by ryanfb** [comment]
FYI, I'm moving house (and just got back from a conference), so I probably won't be able to get around to these until late next week, but I'm assigning myself so they won't fall off my radar.

**Comment by ryanfb** [comment]
All submitted.
