### ISSUE TITLE
 Files not properly processed: Files stuck in Finalize

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#46]
Not had the behaviour before, as far as I can remember. This file is stuck in Finalize. If I open Leiden+, XML or preview, I see the following on the screen:

Die Seite papyri.info funktioniert nicht

Would you please fix this so that I can finalize it: 

 - [x] http://papyri.info/editor/publications/52959/ddb_identifiers/120353/edit

Thanks.

**Comment by ryanfb** [comment]
I've fixed this by re-copying the publication's branch from the board copy of the publication. Any modifications you made to the finalizing copy will need to be re-done, but it should work now.
