### ISSUE TITLE
Files not processed properly: Finalized file stays in my finalize section

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#64]
I finalized 
http://papyri.info/ddbdp/cpr;23;5
at 
<change when="2016-12-15T09:49:56-05:00" who="http://papyri.info/users/james.cowey">Finalized - Ready.</change>
this afternoon.
My finalize section looks at present like this: 
![bildschirmfoto 2016-12-15 um 18 18 03](https://cloud.githubusercontent.com/assets/612992/21234430/e73e05f0-c2f2-11e6-8046-74d5c7570aa9.png)
in other words the file
CPR 23 5 (mgelmaghrabi) 	CPR 23 5 	CPR 23, 5
has not left the section, as it ought to
Furthermore the news feed looks like this:
![bildschirmfoto 2016-12-15 um 18 19 59](https://cloud.githubusercontent.com/assets/612992/21234495/21b2fd30-c2f3-11e6-8b4e-8c4540b813db.png)

I.e. it does not record the action of finalization. 
At one stage I signed out and signed in on a different machine. Initially I was told that I had finalized the text, but then that disappeared.

Just one of the odd things that happened today.

Here is the file affected:

 - [x] http://papyri.info/editor/publications/54745/ddb_identifiers/124609/edit

I do not remember having this happen to me before.

**Comment by ryanfb** [comment]
Manually fixed.
