### ISSUE TITLE
Files not processed properly

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#85]
This concerns biblio files. 
On Thursday of last week at around 12.00 Heidelberg time, I decided to go to admin
http://papyri.info/editor/User/admin
and edit the Biblio board
http://papyri.info/editor/boards/8/edit
My desire had been to remove most of the editorial board briefly to make the assignment of the files have to choose between two finalizers rather than 6 or 7 (that way I would have to make myself finalizers less often). So I clicked away all but myself and Rodney. I continued to work (no signing out and then signing back in again). 
Immediately there was success in my plan. However, after about ten minutes some of the processes started to act funnily. Three broken files will be listed below. On this behaviour I did sign out and sign back in again. I also then sent a mail asking for a reboot of the editor and xSugar, which at the same time seemed to be playing up. Ryan, you did the reboot.
Thu, 24 Aug 2017 15:27:26 +0000 [24.08.2017 17:27:26 CEST]
Thereafter everything started to work OK again. I reinstated most of the members of the board, signed out and signed in again. Since then everything has been fine.
The worst aspect of this is that the branch of the user
http://papyri.info/editor/users/LauraM%C3%BCller
seems to have been affected. When she clicks on Create New Biblio record she gets a we are sorry message and cannot create anything new. Since she is working for me and doing good work, if would be great if you could prioritise looking at her branch and seeing whether you can find conflicts which you could solve so that she can work for me this week (her last week).

**Comment by jcowey** [comment]
Here are the corrupted files which it would be great to have reinstated and assigned to me:

 - [ ] http://papyri.info/editor/publications/60310/biblio_identifiers/136009/edit
 - [ ] http://papyri.info/editor/publications/60316/biblio_identifiers/136015/edit
 - [ ] http://papyri.info/editor/publications/60314/biblio_identifiers/136013/edit

**Comment by ryanfb** [comment]
I've unwedged these publications. The last error I see for Laura clicking "Create New Biblio" seems to be from before the reboot and possibly related to that. If you can have them click "Create New Biblio" again to see if it now works, or generate another error that I can try to trace and fix, that would be great.
