### ISSUE TITLE
Files not properly processed: Finalization worked but traces left hanging

### ISSUE THREAD

**Issue by jcowey** [papyri/sosol#97]
I made the necessary changes to a specific file and the chose the Finalize button (alongside Overview Text HGV), I added our standard comment "Ready" and then I hit the Finalize button again. The file in question is:

http://papyri.info/editor/publications/61693/finalize

after a few seconds the page turned completely blank and has stayed that way (normally we are presented with a page containing the identifiers and a message that the file has been finalized).

I waited until the next sync to see whether the file had gone through. It has:

https://github.com/papyri/idp.data/commit/b315642c24aacf977bcce3defe8303e590cfebdc

That is reflected on the 

http://papyri.info/editor/user/user_dashboard:

![bildschirmfoto 2017-10-20 um 15 46 38](https://user-images.githubusercontent.com/612992/31823962-0317a8d6-b5ae-11e7-8958-efb9091f2f91.png)

The file in question is 
You committed thokru/P.Brem. 37 (about 1 hour ago)

This however is what the editorial board now looks
http://papyri.info/editor/ser/board_dashboard?board_id=1:

![bildschirmfoto 2017-10-20 um 15 48 38](https://user-images.githubusercontent.com/612992/31824089-51a660e6-b5ae-11e7-97de-4bb6db3267a8.png)

As you can see P.Brem. 37 is still sitting there without a finalizer assigned, although this file has been finalized and the results of this can now be seen at

papyri.info/ddbdp/p.brem;;37

I am assuming that this is yet another variety of how the editorial board can get messed up, broken and contribute to slowing etc.

**Comment by jcowey** [comment]
If you did nothing, then you, @ryanfb . Perhaps I was too impatient. I clicked upon the

**Comment by ryanfb** [comment]
No worries. NB: I've been holding off processing any wedged publications until Hugh is done with the repository work.
